name: live-audio-ml
channels:
  - defaults
dependencies:
  - h5py>=2.7,<3
  - hdf5>=1.8,<2
  - matplotlib>=2.2.0,<3
  - mkl>=2018,<2019
  - pip>=9.0.1,<=18.1
  - python=3.6.6
  - scipy=1
  - tensorflow-gpu=1.12
  - pip:
      - asciimatics==1.9.0
      - audiomentations==0.2.0
      - black
      - colorama==0.3.9
      - Keras==2.2.4
      - keras-tcn==2.3.5
      - librosa==0.6.0
      - numpy>=1.14.1,<=1.16
      - Pillow>=5.1.0,<=5.4.0
      - PyAudio==0.2.11
      - pygame==1.9.4
      - tqdm==4.23.4
